### ISSUE TITLE
Nevermind.

### ISSUE THREAD

**Issue by NintendoManiac64** [MarocZan/Better-Ocarina-of-Time#1]
Nevermind.

(if you desperately want to read the original content, I archived it on archive.is)

**Comment by ShadowOne333** [comment]
Why was this closed?

**Comment by NintendoManiac64** [comment]
Because, according to the author of Patcher64+, these are already implemented and I was simply referencing the RHDN listing which is apparently outdated:

https://forums.dolphin-emu.org/Thread-patcher64-tool-v17-0-0-2022-01-29?pid=524011#pid524011
